apiVersion: v1
kind: ConfigMap
metadata:
  name: django
data:
    PORT: "8080"
    STUDENT_NAME: "Boris Jocoy"
    SITE_NAME: "www.borisjocoy.com"
    DATA_DIR: "/data"
    DEBUG: "1"
    POSTGRES_DB: "mysite"
    POSTGRES_HOSTNAME: "postgres-postgresql"
